### ISSUE TITLE
Retina rules are still added when @2x image is missing

### ISSUE THREAD

**Issue by tdhooper** [simonsmith/postcss-at2x#13]
Any objection to checking the @2x version exists before adding the retina rule?

I'd put this behind a flag, as you have done with `detectImageSize`.

**Background**
I'm planning to do a gradual rollout of retina images across our site. Every image background is declared with the same Less mixin which has the `at-2x` keyword, so we'll end up with blank spaces where we have missing @2x versions. I'd like to fallback to the non-retina in this case.

**Comment by simonsmith** [comment]
I see, yeah that makes sense. If you're happy to put together a PR we can move discussion there.
