### ISSUE TITLE
PostCSS 6 output

### ISSUE THREAD

**Issue by langri-sha** [simonsmith/postcss-at2x#19]
I'm using Webpack with `postcss-loader` which is now pinned to use PostCSS 6.

I get the following added to the output, but goes away if I remove the plugin:

```
function before(add) {this.parent.insertBefore(this, add);  return this}
```

**Comment by simonsmith** [comment]
When you say output do you mean the resulting CSS file has the above JS snippet in it?

**Comment by langri-sha** [comment]
Yes, that seems to be added to the declaration values in place of the `at-2x` value.

**Comment by simonsmith** [comment]
I've just published a new version that uses PostCSS 6.x - please see if that fixes the problem. If not can you report back here with a reduced test case so I can reproduce it?

Cheers

**Comment by langri-sha** [comment]
Thanks a lot @simonsmith, I'll try reproducing this and take another look 🔍.

**Comment by langri-sha** [comment]
Perfect 🙌 ❇️!!! Output looks correct on my end now, I think we can safely close this 💪!
