### ISSUE TITLE
Windows 8.1 backslash

### ISSUE THREAD

**Issue by npofopr** [simonsmith/postcss-at2x#2]
After gulp build, output file:

	.logo {
		background: red url('../images/logo.png') no-repeat 0 0;
	}
	@media (min--moz-device-pixel-ratio: 1.5), (-o-min-device-pixel-ratio: 3/2), (-webkit-min-device-pixel-ratio: 1.5), (min-device-pixel-ratio: 1.5), (min-resolution: 144dpi), (min-resolution: 1.5dppx) {
		.logo {
			background: red url('..\images\logo@2x.png') no-repeat 0 0;
		}
	}

https://github.com/npofopr/test-at2x/blob/master/build/style/style.css

What I did wrong?

**Comment by simonsmith** [comment]
Hmm, you're not doing anything wrong. But maybe because `path.join` is setting the slashes differently on windows. If I push a branch can you test it for me?

**Comment by npofopr** [comment]
Of course

**Comment by simonsmith** [comment]
Okay, @npofopr if you could try out the `windows-slash-fix` branch?

    npm install simonsmith/postcss-at2x#windows-slash-fix

**Comment by npofopr** [comment]
Thanks @simonsmith.
After install npm module 'slash' It worked.

https://github.com/npofopr/test-at2x/blob/master/build/style/style.css

**Comment by simonsmith** [comment]
Okay, I'll merge this into master and push a new tag in a bit

**Comment by simonsmith** [comment]
Fixed in 1.2.2
