### ISSUE TITLE
Automatically add background-size

### ISSUE THREAD

**Issue by niksy** [simonsmith/postcss-at2x#4]
If image doesn’t have `background-size` defined, plugin could read image size of provided image and add that to declaration. This could be optional and provided via options, e.g. `{ addBackgroundSize: true }`

Do you think this makes sense or should be left to developer to add manually?

**Comment by simonsmith** [comment]
A good idea, but how would the plugin read the image size?

**Comment by niksy** [comment]
Top of my head: combination of [`postcss-value-parser`](https://www.npmjs.com/package/postcss-value-parser) (which reads background value, specifically `url` part of it) and [`image-size`](https://github.com/image-size/image-size).

**Comment by simonsmith** [comment]
Interesting, I didn't know about `image-size`. I'll certainly take a look. Might be a good addition if it isn't too expensive to run on multiple images.
