### ISSUE TITLE
postcss-at2x with postcss-cssnext nesting support

### ISSUE THREAD

**Issue by zelvinside** [simonsmith/postcss-at2x#5]
hello, i'm trying using at2x feature on cssnext nesting selector. but in not working. check if i wrong.
note: it only work if i not in nested feature.

sorry for my bad english. :) thank you

my code:
(check **nesting** feature for post-cssnext http://cssnext.io/features/#nesting)
```
#logo {
	width: 128px;
	height: 49px;
	display: flex;
	justify-content: center;
	align-items: center;
	
	& span {
		width: 128px;
		height: 18px;
		display: block;
		background: transparent url("../img/lib/logo-mobile.png") at-2x no-repeat;
	}
}
```

**Comment by zelvinside** [comment]
never mind. i solve the problem. hehe :D

**Comment by simonsmith** [comment]
Hey @zelvinside,

Just in case anyone else asks what was the solution? Was it the order of the plugins?
