### ISSUE TITLE
Add option to change resolve path for image

### ISSUE THREAD

**Issue by niksy** [simonsmith/postcss-at2x#9]
By default, image path when calculating image size is resolved by using `process.cwd()` as baseline (https://github.com/simonsmith/postcss-at2x/blob/master/lib/index.js#L91). This is not always the case (maybe never?).

It would be nice to have option to change that and maybe by default use input CSS `from` property (`decl.source.input.from`) or use `process.cwd()` by default and provide source information as callback argument for developers.

E.g. 

```js
resolveImagePath: ( source ) => {
	return process.cwd();
	// `source` contains input CSS information
}
```

**Comment by simonsmith** [comment]
Hey @niksy,

Yes, I remember you mentioning this in your original PR. I was intending to leave it until it became an issue. Do you find yourself needing to change `process.cwd()`?

**Comment by niksy** [comment]
@simonsmith wow, I totally forgot about mentioning that :D yes, I’m currently working on codebase with various input values and this callback could be handy.

**Comment by simonsmith** [comment]
Ha!

Okay, perhaps show how that API would look so I fully understand.

**Comment by simonsmith** [comment]
Also I'd happily add you as a collaborator if you wanted to take a stab at the work. It might make sense from someone actively using the plugin to shape these features.

**Comment by niksy** [comment]
@simonsmith 

OK, so going in more detail, this is the user-defined option with default value

```js
resolveImagePath: ( value, source ) => {
	return path.resolve(process.cwd(), value);
	// `value` is original background-image url value
	// `source` contains input CSS information
}
```

And in module:

```js
function _resolveImagePath ( value, source ) {
	return path.resolve(process.cwd(), value);
}

// ...

function at2x({identifier = '@2x', detectImageSize = false, resolveImagePath = _resolveImagePath} = {}) {

// ...

if ( typeof resolveImagePath === 'function' ) {
	urlValue = resolveImagePath(fp.value, decl.source);
} else {
	urlValue = _resolveImagePath(fp.value, decl.source);
}
```

`_resolveImagePath` is default callback which is also called if passed option is not a function.

What do you think?

**Comment by simonsmith** [comment]
Ah I see. Yes I think something along those lines would work well. Allows it to be flexible.

**Comment by simonsmith** [comment]
We could perhaps do:

```js
function defaultResolveImagePath() {

}

function at2x({resolveImagePath = defaultResolveImagePath}) {

}

urlValue = resolveImagePath(fp.value, decl.source);
```

**Comment by niksy** [comment]
Yes, that’s more descriptive :) Want me to take a stab at PR for this?

**Comment by simonsmith** [comment]
Sure, would be great

**Comment by niksy** [comment]
Hi @simonsmith, sorry for waiting this long to work on this issue.

I’ve created PR for this, but I’m not able to write tests, I’m getting following error from Jest:

```sh
> postcss-at2x@3.0.0 test /Users/niksy/Projects/postcss-at2x
> jest && npm run lint

 FAIL  test/test.js
  ● Test suite failed to run

    SyntaxError: Unexpected reserved word
      
      at transformAndBuildScript (node_modules/jest/node_modules/jest-cli/node_modules/jest-runtime/build/transform.js:320:12)
      at process._tickCallback (node.js:364:9)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.276s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

I’ve tried to work around it, but I was unable to, event after following several issues which explain the exact problem. Do you maybe know what’s wrong?

**Comment by simonsmith** [comment]
@niksy Hmm, odd. It looks like a Babel issue. `babel-jest` is built into Jest now so it should be fine. Have you definitely got latest dependencies? Maybe remove `node_modules` and `yarn install` again.

**Comment by niksy** [comment]
@simonsmith yup, removed and tried again, same issue. Although I haven’t tried with Yarn (don’t use it currently).

I think it’s related to Node version. I’m using Node 4, but I’ve just tried with Node 6 in Docker container and it works as it should. I’ve added tests to the existing commit.
